# Use a imagem oficial do Gradle com JDK 17 para construir nosso aplicativo a partir do código-fonte
FROM gradle:7.4.1-jdk17 as builder

# Copia o código-fonte para o container
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src

# Compila a aplicação
RUN ./gradlew build 

# Usa a imagem do OpenJDK 17 para rodar a aplicação
FROM openjdk:17-slim

EXPOSE 8081

# Copia o jar compilado do builder para o container de produção
COPY --from=builder /home/gradle/src/build/libs/*.jar /app/atv-pond-kotlin-0.0.1-SNAPSHOT.jar

# Executa a aplicação
CMD ["java", "-jar", "/app/atv-pond-kotlin-0.0.1-SNAPSHOT.jar"]